name: capstone_env
channels:
- https://conda.anaconda.org/tlatorre
- defaults
dependencies:
- astroid=1.5.3=py36_0
- bleach=1.5.0=py36_0
- certifi=2016.2.28=py36_0
- colorama=0.3.9=py36_0
- cycler=0.10.0=py36_0
- decorator=4.1.2=py36_0
- entrypoints=0.2.3=py36_0
- html5lib=0.9999999=py36_0
- icu=57.1=vc14_0
- ipykernel=4.6.1=py36_0
- ipython=6.1.0=py36_0
- ipython_genutils=0.2.0=py36_0
- ipywidgets=6.0.0=py36_0
- isort=4.2.15=py36_0
- jedi=0.10.2=py36_2
- jinja2=2.9.6=py36_0
- jpeg=9b=vc14_0
- jsonschema=2.6.0=py36_0
- jupyter=1.0.0=py36_3
- jupyter_client=5.1.0=py36_0
- jupyter_console=5.2.0=py36_0
- jupyter_core=4.3.0=py36_0
- lazy-object-proxy=1.3.1=py36_0
- libpng=1.6.30=vc14_1
- markupsafe=1.0=py36_0
- matplotlib=2.0.2=np113py36_0
- mistune=0.7.4=py36_0
- mkl=2017.0.3=0
- nbconvert=5.2.1=py36_0
- nbformat=4.4.0=py36_0
- notebook=5.0.0=py36_0
- numpy=1.13.1=py36_0
- openssl=1.0.2l=vc14_0
- pandas=0.20.3=py36_0
- pandocfilters=1.4.2=py36_0
- path.py=10.3.1=py36_0
- pickleshare=0.7.4=py36_0
- pip=9.0.1=py36_1
- prompt_toolkit=1.0.15=py36_0
- pygments=2.2.0=py36_0
- pyparsing=2.2.0=py36_0
- pyqt=5.6.0=py36_2
- python=3.6.2=0
- python-dateutil=2.6.1=py36_0
- pytz=2017.2=py36_0
- pyzmq=16.0.2=py36_0
- qt=5.6.2=vc14_6
- qtconsole=4.3.1=py36_0
- requests=2.14.2=py36_0
- scikit-learn=0.19.0=np113py36_0
- scipy=0.19.1=np113py36_0
- setuptools=36.4.0=py36_1
- simplegeneric=0.8.1=py36_1
- singledispatch=3.4.0.3=py36_0
- sip=4.18=py36_0
- six=1.10.0=py36_0
- testpath=0.3.1=py36_0
- tk=8.5.18=vc14_0
- tornado=4.5.2=py36_0
- traitlets=4.3.2=py36_0
- vs2015_runtime=14.0.25420=0
- wcwidth=0.1.7=py36_0
- wheel=0.29.0=py36_0
- widgetsnbextension=3.0.2=py36_0
- wincertstore=0.2=py36_0
- wrapt=1.10.11=py36_0
- zlib=1.2.11=vc14_0
- pip:
  - docutils==0.14
  - enum34==1.1.6
  - graphviz==0.8.1
  - h5py==2.7.1
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-console==5.2.0
  - jupyter-contrib-core==0.3.3
  - jupyter-contrib-nbextensions==0.3.1
  - jupyter-core==4.3.0
  - jupyter-highlight-selected-word==0.0.11
  - jupyter-latex-envs==1.3.8.4
  - jupyter-nbextensions-configurator==0.2.8
  - keras==2.1.1
  - lockfile==0.12.2
  - markdown==2.6.9
  - mccabe==0.6.1
  - nltk==3.2.5
  - prompt-toolkit==1.0.15
  - protobuf==3.5.0.post1
  - pydot==1.2.3
  - pylint==1.7.4
  - python-daemon==2.1.2
  - pyyaml==3.12
  - tensorflow-gpu==1.4.0
  - tensorflow-tensorboard==0.4.0rc3
  - werkzeug==0.12.2
prefix:

